### ISSUE TITLE
Unable to render polygons from name/value dataset from SQL data source

### ISSUE THREAD

**Issue by ensign-nemo** [grafana/grafana-polystat-panel#269] opened 2023-05-25 15:23 UTC
Using a SQL data source, returning a simple name/value pairing, no polygons are shown.

Sample query: 
```
declare @dt datetime = getutcdate()

SELECT   @dt as [time],   'Hello' as [Name],   0 as [Value]
union ALL
select @dt, 'World', 42
```

I would expect this to present two panels
"Hello", value 0
"World", value 42

Nothing is shown in the panel.

Grafana and PolyStat version v8.5.3

Have tried setting the data source "Format" as both "Time series" and "Table" - same result.

**Comment by oshirohugo** [comment] 2023-08-31 10:24
I could not reproduce this issue. In the description it was informed v8.5.3 in the field "Grafana and PolyStat version", which I assumed it was Grafana version.
I tested with:
Grafana version: v8.5.3
Polystat plugin version: 2.1.2
Microsoft SQL Server plugin version: 5.0.0

![Image](https://github.com/grafana/grafana-polystat-panel/assets/5558280/f34a7bc2-8748-4e2b-bd7f-0fe29e0e26ba)

@ensign-nemo could you provide the plugin versions that you are using? You can check it "Server Admin" > "Plugins". Then search for Polystat and Microsoft SQL Server.

**Comment by briangann** [comment] 2023-09-28 18:04
release v2.1.3 includes a fix for this, re-open if you have any problems with it.

**Closed by briangann** 2023-09-28 18:04 UTC
Labels: good first issue, needs investigation, type/bug
