### ISSUE TITLE
v2.1.11 Disable tooltip doesn't work on Grafana 9.5.14

### ISSUE THREAD

**Issue by tiantangkuohai** [grafana/grafana-polystat-panel#388] opened 2024-05-30 01:49 UTC
Looks like there are 2 tooltips for each cell.
<img width="616" alt="image" src="https://github.com/grafana/grafana-polystat-panel/assets/31265288/c6aa8018-32ee-4644-9d1b-c59a238378c9">
Tooltip still display when it is disabled.
<img width="728" alt="image" src="https://github.com/grafana/grafana-polystat-panel/assets/31265288/d33d2a90-f4a3-4ae0-b918-704a992a14a0">

**Comment by briangann** [comment] 2024-05-30 03:53
looks like a regression, will investigate

**Comment by briangann** [comment] 2024-06-09 06:30
have reproduced this and it is specific to Grafana 9.5, a fix is in progress.  It appears that the Portal component may have a bug that leaves the object in the DOM.

**Closed** 2024-06-12 01:21 UTC
Labels: type/bug
