### ISSUE TITLE
&amp; instead of & in clickthrough url

### ISSUE THREAD

**Issue by dequeee** [grafana/grafana-polystat-panel#350] opened 2024-03-06 17:05 UTC
as said in the title, insterting into the clickthrough this url: /d/cluster-load?var-DataSource=a&var-cluster=b

grafana redirects me to this link:

/d/cluster-load?var-DataSource=a& amp ;var-cluster=b
(the & amp ; is spaced beacause github makes it &, but grafana dont)

not filtering the varible cluster.

How can i get this url "/d/cluster-load?var-DataSource=a&var-cluster=b" even when clicked on? because if it has &amp; it dont works not using the correct variable

**Comment by briangann** [comment] 2024-03-06 21:11
that looks like a bug, the string is being encoded when it shouldn't.  i will work on a quick fix for this and make sure there is test coverage for it.

**Comment by dequeee** [comment] 2024-03-07 08:40
allright thank you, then after your fix will be possibile to use &? is this bug frequent or it only happened to me?

**Comment by briangann** [comment] 2024-03-07 13:27
it will be possible to use `&`

passing multiple template variables in the clickthrough url may not be common, but definitely something we should support.

**Comment by briangann** [comment] 2024-03-10 03:39
Need a little clarification for this issue, I tried a few iterations and haven't reproduced it:

With two template variables:
  DataSource (and values a,b,c), with `a` selected
  cluster (and values a,b,c) with `b` selected

The global override url set as:

```
/d/cluster-load?var-DataSource=${DataSource}&var-cluster=${cluster}
```

will generate:

```
/d/cluster-load?var-DataSource=a&var-cluster=b
```

The same applies in an override.

Can you share a dashboard or more detail on what the page variables look like, and the dashboard settings?

**Comment by dequeee** [comment] 2024-03-11 12:17
i'm using the Clickthrough of the composite, i'm not using variables but instead metric variables, as said here https://grafana.com/grafana/plugins/grafana-polystat-panel/.

this is the url i'm trying to use:
/d/ct935dPVk/cluster-load?var-DataSource=${__cell}&var-cluster=${__composite_name}&var-cluster_nodes=All&var-vm_server=All

and this is where pressing the cell of the panel brings me:
/d/ct935dPVk/cluster-load?var-DataSource=EdbPemSvil&amp;var-cluster=CDLEDBGS06&amp;var-cluster_nodes=All&amp;var-vm_server=All&orgId=1


also in the override url or composite url if i only type & it shows &amp; . i'm not using global clickthrough. the variables {__composite_name} and {__cell} displays the right values, is the & the only problem.

Let me know if i can help you bringing more infos. thanks!

**Comment by briangann** [comment] 2024-03-11 12:58
thanks for the detail, i'll work on reproducing it, v2.0.7 fixed a problem with the ${__composite_name} and ${__cell} variables.

**Comment by dequeee** [comment] 2024-03-11 13:07
Thank you very much!

as i said earlier, putting only  "&" in composite url or override url reproduce my exact error. if putting only "&" dont reveal the problem, maybe i have to update the panel, if you already made a patch on this problem, where can i check which version of the panel im using?

**Comment by briangann** [comment] 2024-03-11 13:33
you should get the latest version if you restart grafana, there isn't a good indicator of what version is currently installed/running (i'm trying to get that put into the catalog view for this reason)

**Comment by dequeee** [comment] 2024-03-11 13:59
i've tried creating a new panel with default settings and the same problem happens so i think that isn't related on the former panel settings. 

in the override i use as "Metric Name or RegEx" -> Status {Cluster=".*"}

in the url i only insert & and it displays `&amp;`.

maybe if you try on previus version the problem will reproduce, so i need to schedule a restart and the problem is fixed.

thanks!

**Comment by briangann** [comment] 2024-03-13 02:12
i had to go back to a very old version to reproduce this (before v2), I'm not able to repro on the current release (2.1.7)

**Comment by dequeee** [comment] 2024-03-13 11:32
so i think that the solution is updating the panel. can you confirm that simply restarting the Grafana service is enough to update the panel?

**Comment by tolzhabayev** [comment] 2024-03-13 12:24
@dequeee you have to update it, actually no need to restart usually https://grafana.com/docs/grafana/latest/administration/plugin-management/#update-a-plugin

**Comment by dequeee** [comment] 2024-03-13 12:35
![grafana](https://github.com/grafana/grafana-polystat-panel/assets/162484119/b981a7df-3103-4b00-8a4d-38a6d1c0e7a9)

i've followed the guide, server admin -> plugins -> polystat 

but when i'm on polystat page the only thing it says is " This plugin is not published to grafana.com/plugins and can't be managed via the catalog." and i can't find any update button in it.

Do i have to restart or is there another way to sort it out?

**Comment by dequeee** [comment] 2024-03-13 12:40
it also says that the grafana server isn't able to connect to grafana.com, can this problem prevent me to manual update the panel? if i restart it will update or will do nothing?

**Comment by briangann** [comment] 2024-03-15 13:26
You can download the plugin manually and install it on-prem (extract it into /var/lib/grafana/plugins). 

I'm not sure what kind of grafana installation you have.

The version in the screenshot shows you have v1.2.11 installed which would have quite a number of bugs, and is the angular-based version of the plugin that is not being supported.

**Closed** 2024-05-30 03:55 UTC
Labels: question, type/bug
